apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spatula

resources:
  - namespace.yaml
  - migrate-job.yaml
  - api-deployment.yaml
  - api-service.yaml
  - worker-deployment.yaml
