#!/usr/bin/env -S pnpm tsx
/**
 * Codegen: class-per-code typed errors for @spatula/client.
 *
 * Reads the frozen `ErrorCode` const-object via @spatula/shared (the
 * backward-compat shim — the monorepo ESLint rule blocks value-imports from
 * @spatula/core-types directly), and writes one `SpatulaApiError` subclass
 * per code into `src/errors/generated.ts`.
 *
 * Output is byte-stable: same input → byte-identical output. CI verifies via
 * `pnpm gen:errors && git diff --exit-code packages/client/src/errors/generated.ts`
 * to catch drift between the enum and the committed subclasses (Pitfall #6).
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
// Import ErrorCode VALUE via @spatula/shared. D-10 ESLint rule blocks
// value-imports from @spatula/core-types directly; the shim form is the
// canonical contract.
import { ErrorCode } from '@spatula/shared';

const HEADER = `// GENERATED by scripts/gen-error-classes.ts. Edit @spatula/core-types/src/errors/codes.ts instead.\n// CI verifies via \`pnpm gen:errors && git diff --exit-code\`.\nimport { SpatulaApiError } from './base.js';\n\n`;

function classNameFor(code: string): string {
  // 'JOB.NOT_FOUND' → ['JOB', 'NOT_FOUND'] → ['Job', 'NotFound'] → 'JobNotFoundError'
  return (
    code
      .split(/[._]/)
      .map((p) => p[0] + p.slice(1).toLowerCase())
      .join('') + 'Error'
  );
}

const codeValues = Object.values(ErrorCode);
const lines: string[] = [HEADER];
const mapEntries: string[] = [];

for (const code of codeValues) {
  const cls = classNameFor(code);
  lines.push(
    `export class ${cls} extends SpatulaApiError {\n` +
      `  static readonly code = '${code}';\n` +
      `  constructor(opts: Omit<ConstructorParameters<typeof SpatulaApiError>[0], 'code'>) {\n` +
      `    super({ ...opts, code: '${code}' });\n` +
      `    this.name = '${cls}';\n` +
      `  }\n` +
      `}\n\n`,
  );
  mapEntries.push(`  '${code}': ${cls},`);
}

lines.push(
  `export const ERROR_CLASS_BY_CODE: Record<string, typeof SpatulaApiError> = {\n${mapEntries.join('\n')}\n};\n\n`,
);
lines.push(
  `export function decodeError(envelope: { code: string; message: string; requestId: string; details?: Record<string, unknown> }, status: number): SpatulaApiError {\n  const Ctor = ERROR_CLASS_BY_CODE[envelope.code] ?? SpatulaApiError;\n  return new Ctor({ ...envelope, status });\n}\n`,
);

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, '../src/errors/generated.ts');
writeFileSync(out, lines.join(''));
// eslint-disable-next-line no-console
console.log(`Wrote ${out} (${codeValues.length} classes)`);
