/**
 * Base error class hierarchy for @spatula/client.
 *
 * `SpatulaApiError` is the root of every client-side error. Per-code subclasses
 * are generated by `scripts/gen-error-classes.ts` into `./generated.ts` and
 * COMMITTED to git (D-11). Two well-known special-case subclasses
 * (`SpatulaVersionMismatchError`, `FeatureUnavailableError`) live here because
 * they have semantic meaning beyond their wire ErrorCode.
 */
export interface SpatulaApiErrorOpts {
  code: string;
  message: string;
  status: number;
  requestId: string;
  details?: Record<string, unknown>;
}

export class SpatulaApiError extends Error {
  readonly code: string;
  readonly status: number;
  readonly requestId: string;
  readonly details?: Record<string, unknown>;

  constructor(opts: SpatulaApiErrorOpts) {
    super(opts.message);
    this.name = 'SpatulaApiError';
    this.code = opts.code;
    this.status = opts.status;
    this.requestId = opts.requestId;
    this.details = opts.details;
  }
}

/**
 * Thrown when the server reports VERSION.MISMATCH (HTTP 426). Indicates the
 * client SDK is incompatible with the server's API version contract — the
 * caller should upgrade `@spatula/client` to a version matching the server.
 */
export class SpatulaVersionMismatchError extends SpatulaApiError {
  constructor(opts: SpatulaApiErrorOpts) {
    super(opts);
    this.name = 'SpatulaVersionMismatchError';
  }
}

/**
 * Thrown when the server reports a capability is not provisioned (typically
 * INTERNAL.QUEUE → 503 NOT_CONFIGURED-style errors). The caller should not
 * retry without operator intervention.
 */
export class FeatureUnavailableError extends SpatulaApiError {
  constructor(opts: SpatulaApiErrorOpts) {
    super(opts);
    this.name = 'FeatureUnavailableError';
  }
}
