// GENERATED by scripts/gen-error-classes.ts. Edit @spatula/core-types/src/errors/codes.ts instead.
// CI verifies via `pnpm gen:errors && git diff --exit-code`.
import { SpatulaApiError } from './base.js';

export class JobNotFoundError extends SpatulaApiError {
  static readonly code = 'JOB.NOT_FOUND';
  constructor(opts: Omit<ConstructorParameters<typeof SpatulaApiError>[0], 'code'>) {
    super({ ...opts, code: 'JOB.NOT_FOUND' });
    this.name = 'JobNotFoundError';
  }
}

export class JobConflictError extends SpatulaApiError {
  static readonly code = 'JOB.CONFLICT';
  constructor(opts: Omit<ConstructorParameters<typeof SpatulaApiError>[0], 'code'>) {
    super({ ...opts, code: 'JOB.CONFLICT' });
    this.name = 'JobConflictError';
  }
}

export class JobInvalidStateError extends SpatulaApiError {
  static readonly code = 'JOB.INVALID_STATE';
  constructor(opts: Omit<ConstructorParameters<typeof SpatulaApiError>[0], 'code'>) {
    super({ ...opts, code: 'JOB.INVALID_STATE' });
    this.name = 'JobInvalidStateError';
  }
}

export class ExtractionQuotaExceededError extends SpatulaApiError {
  static readonly code = 'EXTRACTION.QUOTA_EXCEEDED';
  constructor(opts: Omit<ConstructorParameters<typeof SpatulaApiError>[0], 'code'>) {
    super({ ...opts, code: 'EXTRACTION.QUOTA_EXCEEDED' });
    this.name = 'ExtractionQuotaExceededError';
  }
}

export class ExtractionFailedError extends SpatulaApiError {
  static readonly code = 'EXTRACTION.FAILED';
  constructor(opts: Omit<ConstructorParameters<typeof SpatulaApiError>[0], 'code'>) {
    super({ ...opts, code: 'EXTRACTION.FAILED' });
    this.name = 'ExtractionFailedError';
  }
}

export class SchemaNotFoundError extends SpatulaApiError {
  static readonly code = 'SCHEMA.NOT_FOUND';
  constructor(opts: Omit<ConstructorParameters<typeof SpatulaApiError>[0], 'code'>) {
    super({ ...opts, code: 'SCHEMA.NOT_FOUND' });
    this.name = 'SchemaNotFoundError';
  }
}

export class SchemaVersionConflictError extends SpatulaApiError {
  static readonly code = 'SCHEMA.VERSION_CONFLICT';
  constructor(opts: Omit<ConstructorParameters<typeof SpatulaApiError>[0], 'code'>) {
    super({ ...opts, code: 'SCHEMA.VERSION_CONFLICT' });
    this.name = 'SchemaVersionConflictError';
  }
}

export class EntityNotFoundError extends SpatulaApiError {
  static readonly code = 'ENTITY.NOT_FOUND';
  constructor(opts: Omit<ConstructorParameters<typeof SpatulaApiError>[0], 'code'>) {
    super({ ...opts, code: 'ENTITY.NOT_FOUND' });
    this.name = 'EntityNotFoundError';
  }
}

export class ExportNotFoundError extends SpatulaApiError {
  static readonly code = 'EXPORT.NOT_FOUND';
  constructor(opts: Omit<ConstructorParameters<typeof SpatulaApiError>[0], 'code'>) {
    super({ ...opts, code: 'EXPORT.NOT_FOUND' });
    this.name = 'ExportNotFoundError';
  }
}

export class ExportFailedError extends SpatulaApiError {
  static readonly code = 'EXPORT.FAILED';
  constructor(opts: Omit<ConstructorParameters<typeof SpatulaApiError>[0], 'code'>) {
    super({ ...opts, code: 'EXPORT.FAILED' });
    this.name = 'ExportFailedError';
  }
}

export class AuthInvalidTokenError extends SpatulaApiError {
  static readonly code = 'AUTH.INVALID_TOKEN';
  constructor(opts: Omit<ConstructorParameters<typeof SpatulaApiError>[0], 'code'>) {
    super({ ...opts, code: 'AUTH.INVALID_TOKEN' });
    this.name = 'AuthInvalidTokenError';
  }
}

export class AuthMissingTokenError extends SpatulaApiError {
  static readonly code = 'AUTH.MISSING_TOKEN';
  constructor(opts: Omit<ConstructorParameters<typeof SpatulaApiError>[0], 'code'>) {
    super({ ...opts, code: 'AUTH.MISSING_TOKEN' });
    this.name = 'AuthMissingTokenError';
  }
}

export class AuthInsufficientScopeError extends SpatulaApiError {
  static readonly code = 'AUTH.INSUFFICIENT_SCOPE';
  constructor(opts: Omit<ConstructorParameters<typeof SpatulaApiError>[0], 'code'>) {
    super({ ...opts, code: 'AUTH.INSUFFICIENT_SCOPE' });
    this.name = 'AuthInsufficientScopeError';
  }
}

export class ResourceNotFoundError extends SpatulaApiError {
  static readonly code = 'RESOURCE.NOT_FOUND';
  constructor(opts: Omit<ConstructorParameters<typeof SpatulaApiError>[0], 'code'>) {
    super({ ...opts, code: 'RESOURCE.NOT_FOUND' });
    this.name = 'ResourceNotFoundError';
  }
}

export class TenantNotFoundError extends SpatulaApiError {
  static readonly code = 'TENANT.NOT_FOUND';
  constructor(opts: Omit<ConstructorParameters<typeof SpatulaApiError>[0], 'code'>) {
    super({ ...opts, code: 'TENANT.NOT_FOUND' });
    this.name = 'TenantNotFoundError';
  }
}

export class RateLimitExceededError extends SpatulaApiError {
  static readonly code = 'RATE_LIMIT.EXCEEDED';
  constructor(opts: Omit<ConstructorParameters<typeof SpatulaApiError>[0], 'code'>) {
    super({ ...opts, code: 'RATE_LIMIT.EXCEEDED' });
    this.name = 'RateLimitExceededError';
  }
}

export class QuotaExceededError extends SpatulaApiError {
  static readonly code = 'QUOTA.EXCEEDED';
  constructor(opts: Omit<ConstructorParameters<typeof SpatulaApiError>[0], 'code'>) {
    super({ ...opts, code: 'QUOTA.EXCEEDED' });
    this.name = 'QuotaExceededError';
  }
}

export class VersionMismatchError extends SpatulaApiError {
  static readonly code = 'VERSION.MISMATCH';
  constructor(opts: Omit<ConstructorParameters<typeof SpatulaApiError>[0], 'code'>) {
    super({ ...opts, code: 'VERSION.MISMATCH' });
    this.name = 'VersionMismatchError';
  }
}

export class ValidationSchemaError extends SpatulaApiError {
  static readonly code = 'VALIDATION.SCHEMA';
  constructor(opts: Omit<ConstructorParameters<typeof SpatulaApiError>[0], 'code'>) {
    super({ ...opts, code: 'VALIDATION.SCHEMA' });
    this.name = 'ValidationSchemaError';
  }
}

export class ValidationParamsError extends SpatulaApiError {
  static readonly code = 'VALIDATION.PARAMS';
  constructor(opts: Omit<ConstructorParameters<typeof SpatulaApiError>[0], 'code'>) {
    super({ ...opts, code: 'VALIDATION.PARAMS' });
    this.name = 'ValidationParamsError';
  }
}

export class IdempotencyKeyConflictError extends SpatulaApiError {
  static readonly code = 'IDEMPOTENCY.KEY_CONFLICT';
  constructor(opts: Omit<ConstructorParameters<typeof SpatulaApiError>[0], 'code'>) {
    super({ ...opts, code: 'IDEMPOTENCY.KEY_CONFLICT' });
    this.name = 'IdempotencyKeyConflictError';
  }
}

export class WebhookSignatureInvalidError extends SpatulaApiError {
  static readonly code = 'WEBHOOK.SIGNATURE_INVALID';
  constructor(opts: Omit<ConstructorParameters<typeof SpatulaApiError>[0], 'code'>) {
    super({ ...opts, code: 'WEBHOOK.SIGNATURE_INVALID' });
    this.name = 'WebhookSignatureInvalidError';
  }
}

export class InternalErrorError extends SpatulaApiError {
  static readonly code = 'INTERNAL.ERROR';
  constructor(opts: Omit<ConstructorParameters<typeof SpatulaApiError>[0], 'code'>) {
    super({ ...opts, code: 'INTERNAL.ERROR' });
    this.name = 'InternalErrorError';
  }
}

export class InternalTimeoutError extends SpatulaApiError {
  static readonly code = 'INTERNAL.TIMEOUT';
  constructor(opts: Omit<ConstructorParameters<typeof SpatulaApiError>[0], 'code'>) {
    super({ ...opts, code: 'INTERNAL.TIMEOUT' });
    this.name = 'InternalTimeoutError';
  }
}

export class InternalQueueError extends SpatulaApiError {
  static readonly code = 'INTERNAL.QUEUE';
  constructor(opts: Omit<ConstructorParameters<typeof SpatulaApiError>[0], 'code'>) {
    super({ ...opts, code: 'INTERNAL.QUEUE' });
    this.name = 'InternalQueueError';
  }
}

export class InternalNetworkError extends SpatulaApiError {
  static readonly code = 'INTERNAL.NETWORK';
  constructor(opts: Omit<ConstructorParameters<typeof SpatulaApiError>[0], 'code'>) {
    super({ ...opts, code: 'INTERNAL.NETWORK' });
    this.name = 'InternalNetworkError';
  }
}

export const ERROR_CLASS_BY_CODE: Record<string, typeof SpatulaApiError> = {
  'JOB.NOT_FOUND': JobNotFoundError,
  'JOB.CONFLICT': JobConflictError,
  'JOB.INVALID_STATE': JobInvalidStateError,
  'EXTRACTION.QUOTA_EXCEEDED': ExtractionQuotaExceededError,
  'EXTRACTION.FAILED': ExtractionFailedError,
  'SCHEMA.NOT_FOUND': SchemaNotFoundError,
  'SCHEMA.VERSION_CONFLICT': SchemaVersionConflictError,
  'ENTITY.NOT_FOUND': EntityNotFoundError,
  'EXPORT.NOT_FOUND': ExportNotFoundError,
  'EXPORT.FAILED': ExportFailedError,
  'AUTH.INVALID_TOKEN': AuthInvalidTokenError,
  'AUTH.MISSING_TOKEN': AuthMissingTokenError,
  'AUTH.INSUFFICIENT_SCOPE': AuthInsufficientScopeError,
  'RESOURCE.NOT_FOUND': ResourceNotFoundError,
  'TENANT.NOT_FOUND': TenantNotFoundError,
  'RATE_LIMIT.EXCEEDED': RateLimitExceededError,
  'QUOTA.EXCEEDED': QuotaExceededError,
  'VERSION.MISMATCH': VersionMismatchError,
  'VALIDATION.SCHEMA': ValidationSchemaError,
  'VALIDATION.PARAMS': ValidationParamsError,
  'IDEMPOTENCY.KEY_CONFLICT': IdempotencyKeyConflictError,
  'WEBHOOK.SIGNATURE_INVALID': WebhookSignatureInvalidError,
  'INTERNAL.ERROR': InternalErrorError,
  'INTERNAL.TIMEOUT': InternalTimeoutError,
  'INTERNAL.QUEUE': InternalQueueError,
  'INTERNAL.NETWORK': InternalNetworkError,
};

export function decodeError(envelope: { code: string; message: string; requestId: string; details?: Record<string, unknown> }, status: number): SpatulaApiError {
  const Ctor = ERROR_CLASS_BY_CODE[envelope.code] ?? SpatulaApiError;
  return new Ctor({ ...envelope, status });
}
