apiVersion: apps/v1
kind: Deployment
metadata:
  name: spatula-api
  namespace: spatula
spec:
  template:
    spec:
      containers:
        - name: api
          imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spatula-worker
  namespace: spatula
spec:
  template:
    spec:
      containers:
        - name: worker
          imagePullPolicy: IfNotPresent
---
apiVersion: batch/v1
kind: Job
metadata:
  name: spatula-migrate
  namespace: spatula
spec:
  template:
    spec:
      containers:
        - name: migrate
          imagePullPolicy: IfNotPresent
